export const filterData = [
    {
        category: "Experience",
        name: "experience",
        inputType: "radio",
        options: [
            { label: "Freshers", value: "Freshers" },
            { label: "1 - 2 Years", value: "1-2" },
            { label: "2 - 4 Years", value: "2-4" },
            { label: "4 - 6 Years", value: "4-6" },
            { label: "8 - 10 Years", value: "8-10" },
            { label: "10 - 15 Years", value: "10-15" },
            { label: "15+ Years", value: "15+" },
        ],
    },
    {
        category: "Job Type",
        name: "jobType",
        inputType: "checkbox",
        options: [
            { label: "All", value: "All" },
            { label: "Full Time", value: "Full-Time" },
            { label: "Part Time", value: "Part-Time" },
            { label: "Internship", value: "Internship" },
            { label: "Contract", value: "Contract" },
            { label: "Soft Skill", value: "Soft-Skill" },
            { label: "Freelance", value: "Freelance" },
            { label: "Vocational", value: "Vocational" },
            { label: "Apprenticeship", value: "Apprenticeship" },
            { label: "Remote", value: "Remote" },
        ],
    },
    {
        category: "Education",
        name: "educations",
        inputType: "checkbox",
        options: [
            { label: "All", value: "All" },
            { label: "High School", value: "High-School" },
            { label: "Intermediate", value: "Intermediate" },
            { label: "Graduation", value: "Graduation" },
            { label: "Associate Degree", value: "Associate-Degree" },
            { label: "Bachelor Degree", value: "Bachelor-Degree" },
            { label: "Master Degree", value: "Master-Degree" },
            { label: "PhD", value: "Phd" },
        ],
    },
    {
        category: "Industry Type",
        name: "industryType",
        inputType: "radio",
        options: [
            { label: "All", value: "All" },
            { label: "Technical and Engineering", value: "Technical-And-Engineering" },
            { label: "Business and Finance", value: "Business-And-Finance" },
            { label: "Sales, Marketing and Customer Service", value: "Sales,-Marketing-And-Customer-Service" },
            { label: "Education and Training", value: "Education-And-Training" },
            { label: "Legal and Government", value: "Legal-And-Government" },
            { label: "Professional Services", value: "Professional-Services" },
            { label: "Education and Facilities Management", value: "Education-And-Facilities-Management" },
            { label: "Real Estate", value: "Real-Estate" },
            { label: "Retail", value: "Retail" },
            { label: "Technology", value: "Technology" },
            { label: "Telecoms", value: "Telecoms" },
            { label: "Tourism and Leisure", value: "Tourism-And-Leisure" },
            { label: "Wholesale Trade", value: "Wholesale-Trade" },
            { label: "Agriculture and Soft Commodities", value: "Agriculture-And-Soft-Commodities" },
            { label: "Automotive", value: "Automotive" },
            { label: "Aviation", value: "Aviation" },
            { label: "Chemicals", value: "Chemicals" },
            { label: "Conglomerates", value: "Conglomerates" },
            { label: "Construction and Building Materials", value: "Construction-And-Building-Materials" },
            { label: "Consumer Goods", value: "Consumer-Goods" },
            { label: "Apparel and Textiles", value: "Apparel-And-Textiles" },
            { label: "Corporates-Managed Sponsors", value: "Corporates-Managed-Sponsors" },
            { label: "Food", value: "Food" },
            { label: "Beverages and Tobacco", value: "Beverages-And-Tobacco" },
            { label: "Healthcare", value: "Healthcare" },
            { label: "Hotels", value: "Hotels" },
            { label: "Industrials", value: "Industrials" },
            { label: "Land Transport and Logistics", value: "LAnd-Transport-And-Logistics" },
            { label: "Marine", value: "Marine" },
            { label: "Media", value: "Media" },
            { label: "Metals and Mining", value: "Metals-And-Mining" },
            { label: "Oil and Gas", value: "Oil-And-Gas" },
            { label: "Power and Utilities", value: "Power-And-Utilities" },
            { label: "Other", value: "Other" }
        ],
    },
    {
        category: "Organization Type",
        name: "organizationType",
        inputType: "radio",
        options: [
            { label: "All", value: "All" },
            { label: "Federal Government", value: "Federal Government" },
            { label: "County Government", value: "County Government" },
            { label: "City Government", value: "City Government" },
            { label: "State Government", value: "State Government" },
            { label: "Local Government", value: "Local Government" },
            { label: "NGO", value: "NGO" },
            { label: "Private Company", value: "Private Company" },
            { label: "International Agencies", value: "International Agencies" },
            { label: "Airport Authority", value: "Airport Authority" },
        ],
    },
    {
        category: "Job Level",
        name: "jobLevel",
        inputType: "radio",
        options: [
            { label: "Entry Level", value: "Entry-Level" },
            { label: "Mid Level", value: "Mid-Level" },
            { label: "Expert Level", value: "Expert-Level" },
        ],
    },
]

export const trainingFilter = [
    {
        category: "Category",
        name: "category",
        inputType: "checkbox",
        options: [
            { label: "Job Training", value: "Job Training" },
            { label: "Professional Development", value: "Professional Development" },
            { label: "Job Fair", value: "Job Fair" }
        ],
    },
    {
        category: "Format",
        name: "format",
        inputType: "radio",
        options: [
            { label: "Online", value: "online" },
            { label: "In-Person", value: "in_person" }
        ],
    },
]