import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";
import "./globals.css";
import localFont from "next/font/local";
import Providers from "./StoreProvider";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const times_roman = localFont({
  src: "./../fonts/times new roman.ttf",
  variable: "--times-new-roman",
  weight: "100 400",
});
const times_roman_bold = localFont({
  src: "./../fonts/times new roman bold.ttf",
  variable: "--times-new-roman-bold",
  weight: "500 900",
});

export const metadata: Metadata = {
  title: "Remotis Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${geistSans.variable} ${times_roman.className} ${times_roman_bold.variable} antialiased`}
      >
        <NextTopLoader height={1.5} />
        <AntdRegistry>
          <Providers>{children}</Providers>
        </AntdRegistry>
      </body>
    </html>
  );
}
